# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerEnv < Formula
  desc "Per branch docker compose environment manager"
  homepage "https://github.com/marcinhlybin/docker-env"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/marcinhlybin/docker-env/releases/download/v1.0.0/docker-env_1.0.0_darwin_amd64.tar.gz"
      sha256 "09e8285acd87ae9f5460a5b390654edf06055b41cb98f74a91c0674523a564f5"

      def install
        bin.install "docker-env"
      end
    end
    on_arm do
      url "https://github.com/marcinhlybin/docker-env/releases/download/v1.0.0/docker-env_1.0.0_darwin_arm64.tar.gz"
      sha256 "d502067d61ec4164696b395f7f2fb4684087ceeb77ea9450d22f6be2e49ce0e0"

      def install
        bin.install "docker-env"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcinhlybin/docker-env/releases/download/v1.0.0/docker-env_1.0.0_linux_amd64.tar.gz"
        sha256 "05403e9888090229ffa580cc59d79f21ac9f83a2edaced45d2bd6272350031f1"

        def install
          bin.install "docker-env"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcinhlybin/docker-env/releases/download/v1.0.0/docker-env_1.0.0_linux_arm64.tar.gz"
        sha256 "e34323aeb2407148073fb88a64a14d2a7c0a8d6e72c463d4f38565cea5dedc10"

        def install
          bin.install "docker-env"
        end
      end
    end
  end

  test do
    assert_match "#{version}", shell_output("#{bin}/docker-env --version")
  end
end
